import type {
  ConstructionType,
  FinishLevel,
  HouseTemplate,
  SupplierProduct,
} from "./types";

export const CDF_PER_USD = 2850;

export const constructionTypeLabels: Record<ConstructionType, string> = {
  studio: "Studio",
  house_1_bedroom: "Maison 1 chambre",
  house_2_bedroom: "Maison 2 chambres",
  house_3_bedroom: "Maison 3 chambres",
  duplex: "Duplex",
};

export const finishLevelLabels: Record<FinishLevel, string> = {
  economic: "Economique",
  standard: "Standard",
  premium: "Premium",
};

export const supportedCities = [
  "Kinshasa",
  "Lubumbashi",
  "Goma",
  "Kisangani",
  "Mbuji-Mayi",
  "Kolwezi",
];

export const baseCostPerSquareMeterUsd: Record<ConstructionType, number> = {
  studio: 280,
  house_1_bedroom: 310,
  house_2_bedroom: 335,
  house_3_bedroom: 365,
  duplex: 455,
};

export const finishMultipliers: Record<FinishLevel, number> = {
  economic: 0.86,
  standard: 1,
  premium: 1.24,
};

export const cityMultipliers: Record<string, number> = {
  Kinshasa: 1.08,
  Lubumbashi: 1.03,
  Goma: 1.05,
  Kisangani: 0.96,
  "Mbuji-Mayi": 0.92,
  Kolwezi: 1.01,
};

export const contingencyRates: Record<FinishLevel, number> = {
  economic: 0.08,
  standard: 0.1,
  premium: 0.12,
};

export interface MaterialCoefficient {
  materialName: string;
  category: string;
  unit: string;
  quantityPerSquareMeter: number;
  wasteFactor: number;
}

export const materialCoefficients: MaterialCoefficient[] = [
  {
    materialName: "Ciment",
    category: "Gros oeuvre",
    unit: "sac 50kg",
    quantityPerSquareMeter: 1.25,
    wasteFactor: 1.08,
  },
  {
    materialName: "Sable",
    category: "Gros oeuvre",
    unit: "m3",
    quantityPerSquareMeter: 0.2,
    wasteFactor: 1.08,
  },
  {
    materialName: "Gravier",
    category: "Gros oeuvre",
    unit: "m3",
    quantityPerSquareMeter: 0.17,
    wasteFactor: 1.08,
  },
  {
    materialName: "Fer a beton",
    category: "Structure",
    unit: "kg",
    quantityPerSquareMeter: 17,
    wasteFactor: 1.06,
  },
  {
    materialName: "Briques/blocs",
    category: "Maconnerie",
    unit: "piece",
    quantityPerSquareMeter: 23,
    wasteFactor: 1.09,
  },
  {
    materialName: "Toles",
    category: "Toiture",
    unit: "piece",
    quantityPerSquareMeter: 0.32,
    wasteFactor: 1.08,
  },
  {
    materialName: "Bois",
    category: "Charpente",
    unit: "m3",
    quantityPerSquareMeter: 0.024,
    wasteFactor: 1.06,
  },
  {
    materialName: "Peinture",
    category: "Finition",
    unit: "litre",
    quantityPerSquareMeter: 0.62,
    wasteFactor: 1.05,
  },
  {
    materialName: "Carrelage",
    category: "Finition",
    unit: "m2",
    quantityPerSquareMeter: 0.92,
    wasteFactor: 1.07,
  },
  {
    materialName: "Plomberie",
    category: "Technique",
    unit: "kit",
    quantityPerSquareMeter: 0.034,
    wasteFactor: 1.04,
  },
  {
    materialName: "Electricite",
    category: "Technique",
    unit: "kit",
    quantityPerSquareMeter: 0.036,
    wasteFactor: 1.04,
  },
];

export const mockSupplierProducts: SupplierProduct[] = [
  {
    id: "kin-ciment-1",
    supplierName: "Depot Matete Construction",
    city: "Kinshasa",
    district: "Matete",
    materialName: "Ciment",
    category: "Gros oeuvre",
    unitPrice: 10.8,
    currency: "USD",
    unit: "sac 50kg",
    stockAvailable: 1450,
    deliveryDelayDays: 1,
    reliabilityScore: 88,
    active: true,
    validated: true,
  },
  {
    id: "kin-ciment-2",
    supplierName: "Batir Plus Limete",
    city: "Kinshasa",
    district: "Limete",
    materialName: "Ciment",
    category: "Gros oeuvre",
    unitPrice: 10.4,
    currency: "USD",
    unit: "sac 50kg",
    stockAvailable: 620,
    deliveryDelayDays: 2,
    reliabilityScore: 82,
    active: true,
    validated: true,
  },
  {
    id: "lub-ciment-1",
    supplierName: "Katanga Materiaux",
    city: "Lubumbashi",
    district: "Kenya",
    materialName: "Ciment",
    category: "Gros oeuvre",
    unitPrice: 10.1,
    currency: "USD",
    unit: "sac 50kg",
    stockAvailable: 980,
    deliveryDelayDays: 2,
    reliabilityScore: 85,
    active: true,
    validated: true,
  },
  {
    id: "kin-sable-1",
    supplierName: "Granulats Fleuve",
    city: "Kinshasa",
    district: "Kingabwa",
    materialName: "Sable",
    category: "Gros oeuvre",
    unitPrice: 24,
    currency: "USD",
    unit: "m3",
    stockAvailable: 260,
    deliveryDelayDays: 1,
    reliabilityScore: 80,
    active: true,
    validated: true,
  },
  {
    id: "goma-sable-1",
    supplierName: "Nord Kivu Aggregats",
    city: "Goma",
    district: "Katindo",
    materialName: "Sable",
    category: "Gros oeuvre",
    unitPrice: 22,
    currency: "USD",
    unit: "m3",
    stockAvailable: 180,
    deliveryDelayDays: 2,
    reliabilityScore: 78,
    active: true,
    validated: true,
  },
  {
    id: "kin-gravier-1",
    supplierName: "Carriere Ngaliema",
    city: "Kinshasa",
    district: "Ngaliema",
    materialName: "Gravier",
    category: "Gros oeuvre",
    unitPrice: 32,
    currency: "USD",
    unit: "m3",
    stockAvailable: 210,
    deliveryDelayDays: 2,
    reliabilityScore: 84,
    active: true,
    validated: true,
  },
  {
    id: "lub-gravier-1",
    supplierName: "Carriere Lubumbashi Sud",
    city: "Lubumbashi",
    district: "Kamalondo",
    materialName: "Gravier",
    category: "Gros oeuvre",
    unitPrice: 30,
    currency: "USD",
    unit: "m3",
    stockAvailable: 240,
    deliveryDelayDays: 2,
    reliabilityScore: 81,
    active: true,
    validated: true,
  },
  {
    id: "kin-fer-1",
    supplierName: "Acier Congo Trade",
    city: "Kinshasa",
    district: "Gombe",
    materialName: "Fer a beton",
    category: "Structure",
    unitPrice: 1.25,
    currency: "USD",
    unit: "kg",
    stockAvailable: 14000,
    deliveryDelayDays: 2,
    reliabilityScore: 90,
    active: true,
    validated: true,
  },
  {
    id: "kol-fer-1",
    supplierName: "Kolwezi Steel",
    city: "Kolwezi",
    district: "Dilala",
    materialName: "Fer a beton",
    category: "Structure",
    unitPrice: 1.18,
    currency: "USD",
    unit: "kg",
    stockAvailable: 9000,
    deliveryDelayDays: 4,
    reliabilityScore: 83,
    active: true,
    validated: true,
  },
  {
    id: "kin-blocs-1",
    supplierName: "Blocs Nsele",
    city: "Kinshasa",
    district: "Nsele",
    materialName: "Briques/blocs",
    category: "Maconnerie",
    unitPrice: 0.48,
    currency: "USD",
    unit: "piece",
    stockAvailable: 36000,
    deliveryDelayDays: 2,
    reliabilityScore: 86,
    active: true,
    validated: true,
  },
  {
    id: "mbj-blocs-1",
    supplierName: "Kasai Blocs Services",
    city: "Mbuji-Mayi",
    district: "Bipemba",
    materialName: "Briques/blocs",
    category: "Maconnerie",
    unitPrice: 0.42,
    currency: "USD",
    unit: "piece",
    stockAvailable: 22000,
    deliveryDelayDays: 3,
    reliabilityScore: 77,
    active: true,
    validated: true,
  },
  {
    id: "kin-toles-1",
    supplierName: "Toitures Avenue Poids Lourds",
    city: "Kinshasa",
    district: "Kingabwa",
    materialName: "Toles",
    category: "Toiture",
    unitPrice: 8.7,
    currency: "USD",
    unit: "piece",
    stockAvailable: 2400,
    deliveryDelayDays: 1,
    reliabilityScore: 82,
    active: true,
    validated: true,
  },
  {
    id: "goma-toles-1",
    supplierName: "Lac Toiture",
    city: "Goma",
    district: "Himbi",
    materialName: "Toles",
    category: "Toiture",
    unitPrice: 8.4,
    currency: "USD",
    unit: "piece",
    stockAvailable: 1100,
    deliveryDelayDays: 2,
    reliabilityScore: 79,
    active: true,
    validated: true,
  },
  {
    id: "kin-bois-1",
    supplierName: "Bois & Charpente Masina",
    city: "Kinshasa",
    district: "Masina",
    materialName: "Bois",
    category: "Charpente",
    unitPrice: 310,
    currency: "USD",
    unit: "m3",
    stockAvailable: 75,
    deliveryDelayDays: 3,
    reliabilityScore: 81,
    active: true,
    validated: true,
  },
  {
    id: "kis-bois-1",
    supplierName: "Tshopo Bois",
    city: "Kisangani",
    district: "Makiso",
    materialName: "Bois",
    category: "Charpente",
    unitPrice: 280,
    currency: "USD",
    unit: "m3",
    stockAvailable: 95,
    deliveryDelayDays: 4,
    reliabilityScore: 78,
    active: true,
    validated: true,
  },
  {
    id: "kin-peinture-1",
    supplierName: "Coloris Kin",
    city: "Kinshasa",
    district: "Bandalungwa",
    materialName: "Peinture",
    category: "Finition",
    unitPrice: 4.2,
    currency: "USD",
    unit: "litre",
    stockAvailable: 1800,
    deliveryDelayDays: 1,
    reliabilityScore: 84,
    active: true,
    validated: true,
  },
  {
    id: "lub-peinture-1",
    supplierName: "Deco Katanga",
    city: "Lubumbashi",
    district: "Centre-ville",
    materialName: "Peinture",
    category: "Finition",
    unitPrice: 4,
    currency: "USD",
    unit: "litre",
    stockAvailable: 1200,
    deliveryDelayDays: 2,
    reliabilityScore: 82,
    active: true,
    validated: true,
  },
  {
    id: "kin-carrelage-1",
    supplierName: "Sol Design Kin",
    city: "Kinshasa",
    district: "Kasa-Vubu",
    materialName: "Carrelage",
    category: "Finition",
    unitPrice: 9.5,
    currency: "USD",
    unit: "m2",
    stockAvailable: 4200,
    deliveryDelayDays: 2,
    reliabilityScore: 85,
    active: true,
    validated: true,
  },
  {
    id: "goma-carrelage-1",
    supplierName: "Kivu Deco Sol",
    city: "Goma",
    district: "Birere",
    materialName: "Carrelage",
    category: "Finition",
    unitPrice: 9.1,
    currency: "USD",
    unit: "m2",
    stockAvailable: 2500,
    deliveryDelayDays: 2,
    reliabilityScore: 80,
    active: true,
    validated: true,
  },
  {
    id: "kin-plomberie-1",
    supplierName: "Hydro Batiment",
    city: "Kinshasa",
    district: "Limete",
    materialName: "Plomberie",
    category: "Technique",
    unitPrice: 78,
    currency: "USD",
    unit: "kit",
    stockAvailable: 95,
    deliveryDelayDays: 1,
    reliabilityScore: 87,
    active: true,
    validated: true,
  },
  {
    id: "lub-plomberie-1",
    supplierName: "Pro Plomberie Katanga",
    city: "Lubumbashi",
    district: "Ruashi",
    materialName: "Plomberie",
    category: "Technique",
    unitPrice: 74,
    currency: "USD",
    unit: "kit",
    stockAvailable: 70,
    deliveryDelayDays: 2,
    reliabilityScore: 81,
    active: true,
    validated: true,
  },
  {
    id: "kin-electricite-1",
    supplierName: "Elec Pro Kin",
    city: "Kinshasa",
    district: "Gombe",
    materialName: "Electricite",
    category: "Technique",
    unitPrice: 92,
    currency: "USD",
    unit: "kit",
    stockAvailable: 110,
    deliveryDelayDays: 1,
    reliabilityScore: 89,
    active: true,
    validated: true,
  },
  {
    id: "kis-electricite-1",
    supplierName: "Tshopo Electric",
    city: "Kisangani",
    district: "Kabondo",
    materialName: "Electricite",
    category: "Technique",
    unitPrice: 86,
    currency: "USD",
    unit: "kit",
    stockAvailable: 60,
    deliveryDelayDays: 3,
    reliabilityScore: 80,
    active: true,
    validated: true,
  },
];

export const houseTemplates: HouseTemplate[] = [
  {
    id: "studio-compact",
    name: "Studio compact",
    minSurface: 25,
    maxSurface: 35,
    bedrooms: 0,
    rooms: [
      { name: "Piece principale", area: 18 },
      { name: "Kitchenette", area: 5 },
      { name: "Salle d'eau", area: 4 },
    ],
    layout: [
      {
        name: "Piece principale",
        area: 18,
        x: 0,
        y: 0,
        width: 68,
        height: 100,
        color: "#f8d58b",
      },
      {
        name: "Kitchenette",
        area: 5,
        x: 68,
        y: 0,
        width: 32,
        height: 45,
        color: "#9fd5c8",
      },
      {
        name: "Salle d'eau",
        area: 4,
        x: 68,
        y: 45,
        width: 32,
        height: 55,
        color: "#9bb8e8",
      },
    ],
  },
  {
    id: "house-one-bedroom",
    name: "Maison 1 chambre",
    minSurface: 35,
    maxSurface: 55,
    bedrooms: 1,
    rooms: [
      { name: "Salon", area: 16 },
      { name: "Chambre", area: 12 },
      { name: "Cuisine", area: 7 },
      { name: "Salle d'eau", area: 5 },
    ],
    layout: [
      {
        name: "Salon",
        area: 16,
        x: 0,
        y: 0,
        width: 58,
        height: 56,
        color: "#f6c177",
      },
      {
        name: "Chambre",
        area: 12,
        x: 0,
        y: 56,
        width: 58,
        height: 44,
        color: "#b7d68c",
      },
      {
        name: "Cuisine",
        area: 7,
        x: 58,
        y: 0,
        width: 42,
        height: 48,
        color: "#86d1c1",
      },
      {
        name: "Salle d'eau",
        area: 5,
        x: 58,
        y: 48,
        width: 42,
        height: 52,
        color: "#91b7e5",
      },
    ],
  },
  {
    id: "house-two-bedroom",
    name: "Maison 2 chambres",
    minSurface: 55,
    maxSurface: 85,
    bedrooms: 2,
    rooms: [
      { name: "Salon", area: 20 },
      { name: "Chambre 1", area: 12 },
      { name: "Chambre 2", area: 11 },
      { name: "Cuisine", area: 8 },
      { name: "Salle d'eau", area: 5 },
      { name: "Circulation", area: 5 },
    ],
    layout: [
      {
        name: "Salon",
        area: 20,
        x: 0,
        y: 0,
        width: 54,
        height: 52,
        color: "#f6c177",
      },
      {
        name: "Chambre 1",
        area: 12,
        x: 0,
        y: 52,
        width: 35,
        height: 48,
        color: "#b7d68c",
      },
      {
        name: "Chambre 2",
        area: 11,
        x: 35,
        y: 52,
        width: 31,
        height: 48,
        color: "#a6d49f",
      },
      {
        name: "Cuisine",
        area: 8,
        x: 54,
        y: 0,
        width: 46,
        height: 37,
        color: "#86d1c1",
      },
      {
        name: "Salle d'eau",
        area: 5,
        x: 66,
        y: 52,
        width: 34,
        height: 48,
        color: "#91b7e5",
      },
      {
        name: "Circulation",
        area: 5,
        x: 54,
        y: 37,
        width: 46,
        height: 15,
        color: "#ded7c8",
      },
    ],
  },
  {
    id: "house-three-bedroom",
    name: "Maison 3 chambres",
    minSurface: 85,
    maxSurface: 120,
    bedrooms: 3,
    rooms: [
      { name: "Salon", area: 25 },
      { name: "Chambre parentale", area: 15 },
      { name: "Chambre 2", area: 12 },
      { name: "Chambre 3", area: 11 },
      { name: "Cuisine", area: 10 },
      { name: "Salle d'eau", area: 6 },
      { name: "WC visiteurs", area: 3 },
      { name: "Circulation", area: 8 },
    ],
    layout: [
      {
        name: "Salon",
        area: 25,
        x: 0,
        y: 0,
        width: 47,
        height: 55,
        color: "#f6c177",
      },
      {
        name: "Chambre parentale",
        area: 15,
        x: 0,
        y: 55,
        width: 34,
        height: 45,
        color: "#b7d68c",
      },
      {
        name: "Chambre 2",
        area: 12,
        x: 34,
        y: 55,
        width: 28,
        height: 45,
        color: "#a6d49f",
      },
      {
        name: "Chambre 3",
        area: 11,
        x: 62,
        y: 55,
        width: 38,
        height: 45,
        color: "#bddb91",
      },
      {
        name: "Cuisine",
        area: 10,
        x: 47,
        y: 0,
        width: 31,
        height: 38,
        color: "#86d1c1",
      },
      {
        name: "Salle d'eau",
        area: 6,
        x: 78,
        y: 0,
        width: 22,
        height: 38,
        color: "#91b7e5",
      },
      {
        name: "WC visiteurs",
        area: 3,
        x: 78,
        y: 38,
        width: 22,
        height: 17,
        color: "#abc7f1",
      },
      {
        name: "Circulation",
        area: 8,
        x: 47,
        y: 38,
        width: 31,
        height: 17,
        color: "#ded7c8",
      },
    ],
  },
  {
    id: "duplex-family",
    name: "Duplex familial",
    minSurface: 120,
    maxSurface: 220,
    bedrooms: 4,
    rooms: [
      { name: "Salon / sejour", area: 32 },
      { name: "Cuisine", area: 14 },
      { name: "Suite parentale", area: 18 },
      { name: "Chambre 2", area: 13 },
      { name: "Chambre 3", area: 13 },
      { name: "Bureau/chambre", area: 11 },
      { name: "Sanitaires", area: 10 },
      { name: "Escalier", area: 7 },
      { name: "Circulation", area: 12 },
    ],
    layout: [
      {
        name: "Salon / sejour",
        area: 32,
        x: 0,
        y: 0,
        width: 48,
        height: 52,
        color: "#f6c177",
      },
      {
        name: "Cuisine",
        area: 14,
        x: 48,
        y: 0,
        width: 30,
        height: 36,
        color: "#86d1c1",
      },
      {
        name: "Suite parentale",
        area: 18,
        x: 0,
        y: 52,
        width: 34,
        height: 48,
        color: "#b7d68c",
      },
      {
        name: "Chambre 2",
        area: 13,
        x: 34,
        y: 52,
        width: 24,
        height: 48,
        color: "#a6d49f",
      },
      {
        name: "Chambre 3",
        area: 13,
        x: 58,
        y: 52,
        width: 23,
        height: 48,
        color: "#bddb91",
      },
      {
        name: "Bureau/chambre",
        area: 11,
        x: 81,
        y: 52,
        width: 19,
        height: 48,
        color: "#c6dc99",
      },
      {
        name: "Sanitaires",
        area: 10,
        x: 78,
        y: 0,
        width: 22,
        height: 36,
        color: "#91b7e5",
      },
      {
        name: "Escalier",
        area: 7,
        x: 48,
        y: 36,
        width: 30,
        height: 16,
        color: "#d7c7a2",
      },
      {
        name: "Circulation",
        area: 12,
        x: 78,
        y: 36,
        width: 22,
        height: 16,
        color: "#ded7c8",
      },
    ],
  },
];
